# Book configuration
title: "APL Quest Notes"
author: "jgordini"
logo: ""  # No logo
# Repository information
repository:
  url: "https://github.com/jgordini/apl-quest-notes"
  path_to_book: ""
  branch: "main"
# Execution options
execute:
  execute_notebooks: off
# HTML output options
html:
  theme:
    light: true
    dark: false
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true
  favicon: ""
  google_analytics_id: ""
  home_page_in_navbar: true
  baseurl: ""
  extra_navbar: |
    <p>© 2024 jgordini. All rights reserved.</p>
  sidebar:
    collapse_inactive_chapters: true
    collapse_inactive_sections: true
    collapse_on_load: true
  extra_css:
    - _static/custom.css
# LaTeX options
latex:
  latex_engine: pdflatex
# Sphinx configuration
sphinx:
  config:
    html_theme: "sphinx_book_theme"
    html_theme_options:
      show_navbar_depth: 2
    html_sidebars:
      "**": ["search-field.html", "sbt-sidebar-nav.html"]
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
# MyST-Parser options
parse:
  myst_enable_extensions:
    - dollarmath
    - amsmath
    - colon_fence
  myst_heading_anchors: 3
# Launch buttons
launch_buttons:
  binderhub_url: "https://mybinder.org"
  thebe: true
